services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    WechatWorkGroupWelcomeTemplateBundle\DataFixtures\:
        resource: '../../DataFixtures'
        tags: ['doctrine.fixture.orm']
